[build]
  publish = "dist-examples"
  command = "npm run build:examples"

[[redirects]]
  from = "/"
  to = "/examples/vanilla/index.html"
  status = 200

[[redirects]]
  from = "/vanilla"
  to = "/examples/vanilla/index.html"
  status = 200

[[redirects]]
  from = "/react"
  to = "/examples/react/index.html"
  status = 200

[[redirects]]
  from = "/vue"
  to = "/examples/vue/index.html"
  status = 200