[build]
  publish = "docs"
  command = "npm run build"

[[redirects]]
  from = "/vanilla"
  to = "/examples/vanilla/index.html"
  status = 200

[[redirects]]
  from = "/react"
  to = "/examples/react/index.html"
  status = 200

[[redirects]]
  from = "/vue"
  to = "/examples/vue/index.html"
  status = 200

[[redirects]]
  from = "/svelte"
  to = "/examples/svelte/index.html"
  status = 200

[[redirects]]
  from = "/angular"
  to = "/examples/angular/index.html"
  status = 200

[[redirects]]
  from = "/solid"
  to = "/examples/solid/index.html"
  status = 200
